### ISSUE TITLE
[FR] Examples

### ISSUE THREAD

**Issue by Netoen** [Masonjar13/AHK-Library#1]
Hello. Thank you for your library. 
 This is a feature request to show some examples of using functions you provide for better understanding. Say, in a form of comments inside the body of function file. 
 Additionally, comments would be nice (for example this line does that or explaining set of parameters you pass to a function).

**Comment by Masonjar13** [comment]
You aren't the first person to ask, and I've certainly considered it. But it would take a lot of time that I don't have. I do plan to do this, in the form of block comments within each individual file. But don't expect it soon.

I don't have an interest in individual line comments. The idea of this library isn't meant to be educational on the interworkings of the functions or classes, but to provide them to be utilized. Generally, if people know what they're looking for, they'll know how to use most of my library with just the descriptions in the readme. If they wish to understand them in-depth, then I would encourage the idea of learning how to read other peoples code and structure, as I find that is a very valuable skill.
