### ISSUE TITLE
setWindowVol not changing Netflix Window App volume.

### ISSUE THREAD

**Issue by serisly** [Masonjar13/AHK-Library#4]
Hello. Thank you very much for this library. I was wondering if you might have an idea about this issue I encountered.
I came across a roadblock trying to use the setWindowVol with Netflix's windows application. It works perfectly fine when referencing other applications like Spotify or so on, but with Netflix regardless of which reference type (id, pid, class, exe) I use from Windows Spy, it does not change it's value in mixer. I assume it's possible given Netflix has an entry in the volume mixer, however for some reason I can't reference it properly. Any idea how to fix this?
Sorry if I'm not using the issue thing properly it's my first time.

https://github.com/Masonjar13/AHK-Library/blob/833fbba7e120475730ad1953672486174d2e2772/Lib/setWindowVol.ahk#L17C1-L46C2

**Comment by Masonjar13** [comment]
Hey, glad you like the library. Unfortunately, I do not use Netflix so I can't address this issue directly. If this is a Windows app, I think there was something about those that made addressing processes and windows excessively difficult in general. I doubly can't test that, as I uninstall the Windows store on my devices.

Can you run [winInfo()](https://github.com/Masonjar13/AHK-Library/blob/833fbba7e120475730ad1953672486174d2e2772/Lib/winInfo.ahk) and post the output? Also, try checking for and using different running processes for Netflix. The entry you see in the mixer may not be the main process.
